#对象
person:
  name: Lucy
  age: 14
  happy: false
  birth: 2021/05/01
  maps: {k1: v1,k2: v2}
  lists:
    -eat
    -walk
    -sing
  dog:
    name: 旺财
    age: 2
spring:
  profiles:
    active: pro
#查看哪些自动配置类 生效或没有生效
#debug: true
